import { Province, Area, Post } from "@/types";

export interface WardEntry {
  number: number;
  places: string[];
}

export const PROVINCES: Province[] = [
  { id: "wc", name: "Western Cape" },
  { id: "ec", name: "Eastern Cape" },
  { id: "nc", name: "Northern Cape" },
  { id: "fs", name: "Free State" },
  { id: "kzn", name: "KwaZulu-Natal" },
  { id: "nw", name: "North West" },
  { id: "gp", name: "Gauteng" },
  { id: "mp", name: "Mpumalanga" },
  { id: "lp", name: "Limpopo" },
];

export const MUNICIPALITIES: Area[] = [
  // North West
  { id: "nw-1",  name: "Moretele",                    province_id: "nw", province_name: "North West" },
  { id: "nw-2",  name: "Madibeng",                    province_id: "nw", province_name: "North West" },
  { id: "nw-3",  name: "Rustenburg",                  province_id: "nw", province_name: "North West" },
  { id: "nw-4",  name: "Kgetlengrivier",               province_id: "nw", province_name: "North West" },
  { id: "nw-5",  name: "Moses Kotane",                 province_id: "nw", province_name: "North West" },
  { id: "nw-6",  name: "Setla-Kgobi",                  province_id: "nw", province_name: "North West" },
  { id: "nw-7",  name: "Tswaing",                      province_id: "nw", province_name: "North West" },
  { id: "nw-8",  name: "Mafikeng",                     province_id: "nw", province_name: "North West" },
  { id: "nw-9",  name: "Ditsobotla",                   province_id: "nw", province_name: "North West" },
  { id: "nw-10", name: "Zeerust",                      province_id: "nw", province_name: "North West" },
  { id: "nw-11", name: "Kagisano",                     province_id: "nw", province_name: "North West" },
  { id: "nw-12", name: "Naledi",                       province_id: "nw", province_name: "North West" },
  { id: "nw-13", name: "Mamusa",                       province_id: "nw", province_name: "North West" },
  { id: "nw-14", name: "Greater Taung",                province_id: "nw", province_name: "North West" },
  { id: "nw-15", name: "Molopo",                       province_id: "nw", province_name: "North West" },
  { id: "nw-16", name: "Lekwa-Teemane",                province_id: "nw", province_name: "North West" },
  { id: "nw-17", name: "Ventersdorp",                  province_id: "nw", province_name: "North West" },
  { id: "nw-18", name: "Potchefstroom",                province_id: "nw", province_name: "North West" },
  { id: "nw-19", name: "City Council of Klerksdorp",   province_id: "nw", province_name: "North West" },
  { id: "nw-20", name: "Maquassi Hills",               province_id: "nw", province_name: "North West" },
  { id: "nw-21", name: "Moshaweng",                    province_id: "nw", province_name: "North West" },
  { id: "nw-22", name: "Pilansberg National Park",     province_id: "nw", province_name: "North West" },
];

// Ward data keyed by municipality id (North West)
export const WARDS: Record<string, WardEntry[]> = {
  // Moretele (nw-1) — 22 wards
  "nw-1": [
    { number: 1,  places: ["Mathibestad"] },
    { number: 2,  places: ["Lebotloane", "Lebotloane Ext"] },
    { number: 3,  places: ["Ramotse Village"] },
    { number: 4,  places: ["Mmakau"] },
    { number: 5,  places: ["Motla Village"] },
    { number: 6,  places: ["Roodekuil"] },
    { number: 7,  places: ["Moretele Village"] },
    { number: 8,  places: ["Sephaku"] },
    { number: 9,  places: ["Rooifontein"] },
    { number: 10, places: ["Maboloka"] },
    { number: 11, places: ["Olifantsnek"] },
    { number: 12, places: ["Swartkoppies"] },
    { number: 13, places: ["Soutpan"] },
    { number: 14, places: ["Makapanstad North"] },
    { number: 15, places: ["Makapanstad South"] },
    { number: 16, places: ["Jericho Village"] },
    { number: 17, places: ["Hebron"] },
    { number: 18, places: ["Maupye"] },
    { number: 19, places: ["Sandfontein"] },
    { number: 20, places: ["Kgabalatsane"] },
    { number: 21, places: ["Stinkwater Section"] },
    { number: 22, places: ["Mabopane East"] },
  ],

  // Madibeng (nw-2) — 32 wards
  "nw-2": [
    { number: 1,  places: ["Brits CBD", "Brits Central"] },
    { number: 2,  places: ["Brits North", "Brits Ext 10"] },
    { number: 3,  places: ["Letlhabile"] },
    { number: 4,  places: ["Letlhabile North"] },
    { number: 5,  places: ["Swartwater"] },
    { number: 6,  places: ["Rhenosterfontein"] },
    { number: 7,  places: ["Mmakautswe"] },
    { number: 8,  places: ["Mothotlung"] },
    { number: 9,  places: ["Mothotlung Ext"] },
    { number: 10, places: ["Schoemansville", "Hartbeespoort"] },
    { number: 11, places: ["Ifafi", "Kosmos"] },
    { number: 12, places: ["Broederstroom", "Melodie"] },
    { number: 13, places: ["Rietfontein"] },
    { number: 14, places: ["Pienaarsrivier"] },
    { number: 15, places: ["Remhoogte"] },
    { number: 16, places: ["Mooinooi", "Mooinooi Ext"] },
    { number: 17, places: ["Mnandi Village"] },
    { number: 18, places: ["Numbi"] },
    { number: 19, places: ["Sonderwater"] },
    { number: 20, places: ["Majakaneng"] },
    { number: 21, places: ["Mmasebudule"] },
    { number: 22, places: ["Mogono"] },
    { number: 23, places: ["Damaraland"] },
    { number: 24, places: ["Klipdam"] },
    { number: 25, places: ["Koedoeskop"] },
    { number: 26, places: ["Rooiwal"] },
    { number: 27, places: ["Tarlton"] },
    { number: 28, places: ["Vyfhoek"] },
    { number: 29, places: ["Bodibe"] },
    { number: 30, places: ["Klerkskraal"] },
    { number: 31, places: ["Rietgat"] },
    { number: 32, places: ["Hekpoort"] },
  ],

  // Rustenburg (nw-3) — 35 wards
  "nw-3": [
    { number: 1,  places: ["Rustenburg CBD", "Rustenburg Central"] },
    { number: 2,  places: ["Cashan", "Safari Gardens"] },
    { number: 3,  places: ["Boitekong"] },
    { number: 4,  places: ["Boitekong Ext 4", "Boitekong Ext 5"] },
    { number: 5,  places: ["Tlhabane"] },
    { number: 6,  places: ["Tlhabane West", "Tlhabane Ext"] },
    { number: 7,  places: ["Temba Village", "Temba Section B"] },
    { number: 8,  places: ["Meriting", "Meriting Ext"] },
    { number: 9,  places: ["Phokeng Village"] },
    { number: 10, places: ["Chaneng Village"] },
    { number: 11, places: ["Chaneng Ext", "Chaneng Section C"] },
    { number: 12, places: ["Luka Village"] },
    { number: 13, places: ["Luka Section B", "Kanana Park"] },
    { number: 14, places: ["Mfidikwe Village"] },
    { number: 15, places: ["Modikwe Village"] },
    { number: 16, places: ["Letlhabile North"] },
    { number: 17, places: ["Letlhabile South", "Letlhabile Ext"] },
    { number: 18, places: ["Waterfall East", "Waterfall"] },
    { number: 19, places: ["Mosenthal", "Waterval"] },
    { number: 20, places: ["Tonota Village"] },
    { number: 21, places: ["Marikana", "Marikana Ext 1"] },
    { number: 22, places: ["Nkaneng", "Nkaneng Ext"] },
    { number: 23, places: ["Wonderkop", "Wonderkop Ext 1"] },
    { number: 24, places: ["Western Platinum Area", "Jagvlakte"] },
    { number: 25, places: ["Kroondal", "Kroondal Ext"] },
    { number: 26, places: ["Hartebeestfontein"] },
    { number: 27, places: ["Bethel Village"] },
    { number: 28, places: ["Bethanie", "Buffelshoek"] },
    { number: 29, places: ["Bapong Village"] },
    { number: 30, places: ["Mogosane Village"] },
    { number: 31, places: ["Molatedi Village"] },
    { number: 32, places: ["Saulspoort"] },
    { number: 33, places: ["Stinkwater", "Sunway City"] },
    { number: 34, places: ["Lefaragatlhe Village"] },
    { number: 35, places: ["Marikana Ext 3", "Wonderkop Ext 3"] },
  ],

  // Kgetlengrivier (nw-4) — 14 wards
  "nw-4": [
    { number: 1,  places: ["Koster CBD"] },
    { number: 2,  places: ["Koster North"] },
    { number: 3,  places: ["Syferbult"] },
    { number: 4,  places: ["Mantserre"] },
    { number: 5,  places: ["Motlhabe"] },
    { number: 6,  places: ["Slapkraal"] },
    { number: 7,  places: ["Derby"] },
    { number: 8,  places: ["Zeekoegat"] },
    { number: 9,  places: ["Roodekop"] },
    { number: 10, places: ["Boshoek"] },
    { number: 11, places: ["Swartruggens"] },
    { number: 12, places: ["Witkop"] },
    { number: 13, places: ["Klipfontein"] },
    { number: 14, places: ["Goedehoop"] },
  ],

  // Moses Kotane (nw-5) — 28 wards
  "nw-5": [
    { number: 1,  places: ["Mogwase", "Mogwase Ext"] },
    { number: 2,  places: ["Tlokwe Village"] },
    { number: 3,  places: ["Mabaalstad"] },
    { number: 4,  places: ["Ledig"] },
    { number: 5,  places: ["Tsitsing Village"] },
    { number: 6,  places: ["Mmatau"] },
    { number: 7,  places: ["Manthestad"] },
    { number: 8,  places: ["Mabodisa"] },
    { number: 9,  places: ["Bafokeng Village"] },
    { number: 10, places: ["Sun City Area", "Mankwe"] },
    { number: 11, places: ["Masenya"] },
    { number: 12, places: ["Motlhabe East"] },
    { number: 13, places: ["Ntswaneng"] },
    { number: 14, places: ["Motswedi"] },
    { number: 15, places: ["Mokgalwaneng"] },
    { number: 16, places: ["Swartplaas"] },
    { number: 17, places: ["Mmakubu"] },
    { number: 18, places: ["Tlhabologang"] },
    { number: 19, places: ["Legkraal"] },
    { number: 20, places: ["Seolong"] },
    { number: 21, places: ["Madikwe Village"] },
    { number: 22, places: ["Molatedi"] },
    { number: 23, places: ["Ratshidi Village"] },
    { number: 24, places: ["Matlaro"] },
    { number: 25, places: ["Mmadinare"] },
    { number: 26, places: ["Mokgalwaneng South"] },
    { number: 27, places: ["Kameelhoek"] },
    { number: 28, places: ["Sikwane"] },
  ],

  // Setla-Kgobi (nw-6) — 10 wards
  "nw-6": [
    { number: 1,  places: ["Setlagole"] },
    { number: 2,  places: ["Tswelelang"] },
    { number: 3,  places: ["Tikwana"] },
    { number: 4,  places: ["Lehurutshe"] },
    { number: 5,  places: ["Madibogo"] },
    { number: 6,  places: ["Gopane"] },
    { number: 7,  places: ["Bray"] },
    { number: 8,  places: ["Atamelang"] },
    { number: 9,  places: ["Doornpan"] },
    { number: 10, places: ["Driefontein"] },
  ],

  // Tswaing (nw-7) — 15 wards
  "nw-7": [
    { number: 1,  places: ["Delareyville CBD"] },
    { number: 2,  places: ["Delareyville North"] },
    { number: 3,  places: ["Uitkyk"] },
    { number: 4,  places: ["Sannieshof"] },
    { number: 5,  places: ["Shaleng"] },
    { number: 6,  places: ["Ottosdal"] },
    { number: 7,  places: ["Makgobistad"] },
    { number: 8,  places: ["Louwna"] },
    { number: 9,  places: ["Geysdorp"] },
    { number: 10, places: ["Rietpan"] },
    { number: 11, places: ["Itsoseng"] },
    { number: 12, places: ["Amalia"] },
    { number: 13, places: ["Mooifontein"] },
    { number: 14, places: ["Witpan"] },
    { number: 15, places: ["Wolmaransstad Area"] },
  ],

  // Mafikeng (nw-8) — 22 wards
  "nw-8": [
    { number: 1,  places: ["Mafikeng CBD", "Mmabatho"] },
    { number: 2,  places: ["Montshiwa", "Montshiwa Stad"] },
    { number: 3,  places: ["Ramosadi"] },
    { number: 4,  places: ["Unit 3", "Unit 4"] },
    { number: 5,  places: ["Mabopane", "Mabopane Ext"] },
    { number: 6,  places: ["Rooigrond"] },
    { number: 7,  places: ["Danville"] },
    { number: 8,  places: ["Lomanyaneng"] },
    { number: 9,  places: ["Lotlhakane"] },
    { number: 10, places: ["Modimola"] },
    { number: 11, places: ["Logageng"] },
    { number: 12, places: ["Seweding"] },
    { number: 13, places: ["Disaneng"] },
    { number: 14, places: ["Motswedi"] },
    { number: 15, places: ["Mareetsane"] },
    { number: 16, places: ["Mmanditlane"] },
    { number: 17, places: ["Sethlabetsi"] },
    { number: 18, places: ["Lokaleng"] },
    { number: 19, places: ["Lekubu"] },
    { number: 20, places: ["Mmabatho Unit 10"] },
    { number: 21, places: ["Matsheng"] },
    { number: 22, places: ["Itsoseng"] },
    { number: 23, places: ["Lotlhakane"] },
    { number: 24, places: ["Naawpoort","UitKyk","Mooifontein","Goedgevonden"] },
    { number: 25, places: ["Makouspan","Gelukspan","Driehoek","Kaalpan","Nooitgedacht","Mandela park"] },
    { number: 26, places: ["Madibe"] },
    { number: 27, places: ["Bethel","Schoongezicht","Matshepe","Matlhonyane","Dithakong"] },
    { number: 28, places: ["Signal Hill","Mahikeng Outlying","Molelwane"] },
    { number: 29, places: ["Aslaagte","Top Vilage","Lonely Park","Riviera Park"] },
    { number: 30, places: ["Motlhabeng","Dibate"] },
    { number: 31, places: ["Letlhakane","Lotlhakane"] },
    { number: 32, places: ["Setumo Park","leopard Park"] },
    { number: 33, places: ["Unit Something"] },
    { number: 34, places: ["Magogoe"] },
    { number: 35, places: ["Setlopo","Lomanyaneng"] },
  ],

  // Ditsobotla (nw-9) — 14 wards
  "nw-9": [
    { number: 1,  places: ["Lichtenburg CBD"] },
    { number: 2,  places: ["Lichtenburg North"] },
    { number: 3,  places: ["Boikhutso"] },
    { number: 4,  places: ["Tlhabologang"] },
    { number: 5,  places: ["Itsoseng"] },
    { number: 6,  places: ["Coligny"] },
    { number: 7,  places: ["Biesiesvlei"] },
    { number: 8,  places: ["Vorstershoop"] },
    { number: 9,  places: ["Kopela"] },
    { number: 10, places: ["Mooifontein"] },
    { number: 11, places: ["Vermaas"] },
    { number: 12, places: ["Atamelang"] },
    { number: 13, places: ["Migdol"] },
    { number: 14, places: ["Sannieshof Area"] },
  ],

  // Zeerust / Ramotshere Moiloa (nw-10) — 15 wards
  "nw-10": [
    { number: 1,  places: ["Zeerust CBD"] },
    { number: 2,  places: ["Zeerust North", "Gopane"] },
    { number: 3,  places: ["Motswedi"] },
    { number: 4,  places: ["Lehurutshe"] },
    { number: 5,  places: ["Biesiesvlei"] },
    { number: 6,  places: ["Kraaipan"] },
    { number: 7,  places: ["Madibogo"] },
    { number: 8,  places: ["Supingstad"] },
    { number: 9,  places: ["Khunotswana"] },
    { number: 10, places: ["Lekgalong"] },
    { number: 11, places: ["Dinokana"] },
    { number: 12, places: ["Kopfontein"] },
    { number: 13, places: ["Ottoshoop"] },
    { number: 14, places: ["Skilpadfontein"] },
    { number: 15, places: ["Swartsloot"] },
  ],

  // Kagisano-Molopo (nw-11) — 14 wards
  "nw-11": [
    { number: 1,  places: ["Ganyesa"] },
    { number: 2,  places: ["Stella"] },
    { number: 3,  places: ["Tosca"] },
    { number: 4,  places: ["Morokweng"] },
    { number: 5,  places: ["Heuningvlei"] },
    { number: 6,  places: ["Tlhagwane"] },
    { number: 7,  places: ["Batlharos"] },
    { number: 8,  places: ["Makobo"] },
    { number: 9,  places: ["Khuis"] },
    { number: 10, places: ["Disaneng"] },
    { number: 11, places: ["Louwna"] },
    { number: 12, places: ["Seodin"] },
    { number: 13, places: ["Riemvasmaak"] },
    { number: 14, places: ["Vryburg Area"] },
  ],

  // Naledi (nw-12) — 9 wards
  "nw-12": [
    { number: 1, places: ["Vryburg CBD"] },
    { number: 2, places: ["Vryburg North", "Vryburg Ext"] },
    { number: 3, places: ["Huhudi"] },
    { number: 4, places: ["Jan Kempdorp Area"] },
    { number: 5, places: ["Delportshoop"] },
    { number: 6, places: ["Tsineng"] },
    { number: 7, places: ["Laxey"] },
    { number: 8, places: ["Amalia"] },
    { number: 9, places: ["Vanzylsrus"] },
  ],

  // Mamusa (nw-13) — 9 wards
  "nw-13": [
    { number: 1, places: ["Schweizer-Reneke CBD"] },
    { number: 2, places: ["Schweizer-Reneke North"] },
    { number: 3, places: ["Ipelegeng"] },
    { number: 4, places: ["Makwassie"] },
    { number: 5, places: ["Wolmaransstad"] },
    { number: 6, places: ["Deelpan"] },
    { number: 7, places: ["Vlakfontein"] },
    { number: 8, places: ["Rietgat"] },
    { number: 9, places: ["Migdol Area"] },
  ],

  // Greater Taung (nw-14) — 28 wards
  "nw-14": [
    { number: 1,  places: ["Taung CBD"] },
    { number: 2,  places: ["Taung North", "Pudumong"] },
    { number: 3,  places: ["Taung East"] },
    { number: 4,  places: ["Magwegwe"] },
    { number: 5,  places: ["Reivilo"] },
    { number: 6,  places: ["Pampierstad"] },
    { number: 7,  places: ["Hartswater"] },
    { number: 8,  places: ["Jan Kempdorp"] },
    { number: 9,  places: ["Warrenton"] },
    { number: 10, places: ["Riverton"] },
    { number: 11, places: ["Griekwastad"] },
    { number: 12, places: ["Batlharos Village"] },
    { number: 13, places: ["Dithakong"] },
    { number: 14, places: ["Noe"] },
    { number: 15, places: ["Tswelelang"] },
    { number: 16, places: ["Ga-Moshoeshoe"] },
    { number: 17, places: ["Tlhogong"] },
    { number: 18, places: ["Tsineng Area"] },
    { number: 19, places: ["Mothibistad"] },
    { number: 20, places: ["Gakhibi"] },
    { number: 21, places: ["Moshaweng"] },
    { number: 22, places: ["Laxey Area"] },
    { number: 23, places: ["Kuruman Area"] },
    { number: 24, places: ["Morokweng Area"] },
    { number: 25, places: ["Heuningvlei Area"] },
    { number: 26, places: ["Ganyesa Area"] },
    { number: 27, places: ["Danielskuil"] },
    { number: 28, places: ["Dikgatlong"] },
  ],

  // Molopo (nw-15) — 13 wards
  "nw-15": [
    { number: 1,  places: ["Bray"] },
    { number: 2,  places: ["Tosca Area"] },
    { number: 3,  places: ["Stella Area"] },
    { number: 4,  places: ["Batlharos"] },
    { number: 5,  places: ["Huhudi Area"] },
    { number: 6,  places: ["Morokweng"] },
    { number: 7,  places: ["Khuis"] },
    { number: 8,  places: ["Hotazel"] },
    { number: 9,  places: ["Lohatlha"] },
    { number: 10, places: ["Dithakong"] },
    { number: 11, places: ["Noe"] },
    { number: 12, places: ["Vanzylsrus Area"] },
    { number: 13, places: ["Ganyesa East"] },
  ],

  // Lekwa-Teemane (nw-16) — 12 wards
  "nw-16": [
    { number: 1,  places: ["Christiana CBD"] },
    { number: 2,  places: ["Christiana North"] },
    { number: 3,  places: ["Bloemhof"] },
    { number: 4,  places: ["Boitumelo"] },
    { number: 5,  places: ["Geluksoord"] },
    { number: 6,  places: ["Spitskop"] },
    { number: 7,  places: ["Hertzogville"] },
    { number: 8,  places: ["Acheronville"] },
    { number: 9,  places: ["Pampierstad Area"] },
    { number: 10, places: ["Windsorton"] },
    { number: 11, places: ["Rooigrond"] },
    { number: 12, places: ["Wolmaransstad Area"] },
  ],

  // Ventersdorp (nw-17) — 12 wards
  "nw-17": [
    { number: 1,  places: ["Ventersdorp CBD"] },
    { number: 2,  places: ["Ventersdorp North"] },
    { number: 3,  places: ["Tshing"] },
    { number: 4,  places: ["Tlhabologang"] },
    { number: 5,  places: ["Khuma"] },
    { number: 6,  places: ["Boikhutso"] },
    { number: 7,  places: ["Koster Area"] },
    { number: 8,  places: ["Tarlton Area"] },
    { number: 9,  places: ["Kroondal Area"] },
    { number: 10, places: ["Marikana Area"] },
    { number: 11, places: ["Klerksdorp Road"] },
    { number: 12, places: ["Potchefstroom Road Area"] },
  ],

  // Potchefstroom / JB Marks (nw-18) — 22 wards
  "nw-18": [
    { number: 1,  places: ["Potchefstroom CBD", "Central"] },
    { number: 2,  places: ["Potchefstroom North", "Park"] },
    { number: 3,  places: ["Ikageng"] },
    { number: 4,  places: ["Ikageng Ext 5"] },
    { number: 5,  places: ["Ikageng Ext 11"] },
    { number: 6,  places: ["Promosa"] },
    { number: 7,  places: ["Mooivlei"] },
    { number: 8,  places: ["Mohadin"] },
    { number: 9,  places: ["Grimbeeckpark", "Callie Human"] },
    { number: 10, places: ["Ramotse"] },
    { number: 11, places: ["Boskop"] },
    { number: 12, places: ["Potchefstroom South"] },
    { number: 13, places: ["Wilkoppies", "Dassierand"] },
    { number: 14, places: ["Vyfhoek"] },
    { number: 15, places: ["Townlands"] },
    { number: 16, places: ["Baillie Park"] },
    { number: 17, places: ["Westdene", "Kingswood"] },
    { number: 18, places: ["Die Bult", "Universitas"] },
    { number: 19, places: ["Mooiwater"] },
    { number: 20, places: ["Hydepark"] },
    { number: 21, places: ["Superbia", "Alabama"] },
    { number: 22, places: ["Klerksdorp Road Area"] },
  ],

  // City Council of Klerksdorp / JB Marks (nw-19) — 35 wards
  "nw-19": [
    { number: 1,  places: ["Klerksdorp CBD", "Klerksdorp Central"] },
    { number: 2,  places: ["Roosheuwel", "Newtown"] },
    { number: 3,  places: ["Alabama", "Meiringspark"] },
    { number: 4,  places: ["Jouberton"] },
    { number: 5,  places: ["Jouberton Ext 4"] },
    { number: 6,  places: ["Jouberton Ext 12"] },
    { number: 7,  places: ["Tigane"] },
    { number: 8,  places: ["Khuma"] },
    { number: 9,  places: ["Kanana"] },
    { number: 10, places: ["Stilfontein"] },
    { number: 11, places: ["Orkney"] },
    { number: 12, places: ["Hartebeesfontein"] },
    { number: 13, places: ["Freemanville", "Klerksdorp North"] },
    { number: 14, places: ["Wilkoppies"] },
    { number: 15, places: ["Flamwood"] },
    { number: 16, places: ["Park Extension"] },
    { number: 17, places: ["La Hoff"] },
    { number: 18, places: ["Townview"] },
    { number: 19, places: ["Westdene"] },
    { number: 20, places: ["Tasbetrand"] },
    { number: 21, places: ["Klerksdorp South"] },
    { number: 22, places: ["Boikhutsong"] },
    { number: 23, places: ["Mooifontein"] },
    { number: 24, places: ["Klerksdorp Ext 16"] },
    { number: 25, places: ["Voortrekker Area"] },
    { number: 26, places: ["Stilfontein Ext"] },
    { number: 27, places: ["Matlosana"] },
    { number: 28, places: ["Turffontein"] },
    { number: 29, places: ["Platfontein"] },
    { number: 30, places: ["Orkney Ext"] },
    { number: 31, places: ["Kanana Ext"] },
    { number: 32, places: ["Jouberton East"] },
    { number: 33, places: ["Carletonville Area"] },
    { number: 34, places: ["Klerksdorp North"] },
    { number: 35, places: ["Klerksdorp West"] },
  ],

  // Maquassi Hills (nw-20) — 18 wards
  "nw-20": [
    { number: 1,  places: ["Wolmaransstad CBD"] },
    { number: 2,  places: ["Wolmaransstad North"] },
    { number: 3,  places: ["Ipelegeng"] },
    { number: 4,  places: ["Makwassie"] },
    { number: 5,  places: ["Leeudoringstad"] },
    { number: 6,  places: ["Tswelelang"] },
    { number: 7,  places: ["Deelpan"] },
    { number: 8,  places: ["Ventersdorp Area"] },
    { number: 9,  places: ["Christiana Area"] },
    { number: 10, places: ["Bloemhof Area"] },
    { number: 11, places: ["Witpoortjie"] },
    { number: 12, places: ["Arendsnes"] },
    { number: 13, places: ["Hartbees"] },
    { number: 14, places: ["Vlakfontein"] },
    { number: 15, places: ["Diepdale"] },
    { number: 16, places: ["Migdol"] },
    { number: 17, places: ["Nooitgedacht"] },
    { number: 18, places: ["Schweizer-Reneke Area"] },
  ],

  // Moshaweng (nw-21) — 15 wards
  "nw-21": [
    { number: 1,  places: ["Kuruman CBD"] },
    { number: 2,  places: ["Kuruman North"] },
    { number: 3,  places: ["Mothibistad"] },
    { number: 4,  places: ["Mapoteng"] },
    { number: 5,  places: ["Ditshoswane"] },
    { number: 6,  places: ["Seodin"] },
    { number: 7,  places: ["Manthe"] },
    { number: 8,  places: ["Wrenchville"] },
    { number: 9,  places: ["Gamopedi"] },
    { number: 10, places: ["Gamoep"] },
    { number: 11, places: ["Gatlhose"] },
    { number: 12, places: ["Danielskuil"] },
    { number: 13, places: ["Lime Acres"] },
    { number: 14, places: ["Olifantshoek"] },
    { number: 15, places: ["John Taolo Gaetsewe"] },
  ],
};

export const MOCK_POSTS: Post[] = [
  {
    id: "1",
    area_id: "nw-3",
    area_name: "Rustenburg",
    province_name: "North West",
    user_id: "anon",
    category: "alert",
    content: "Suspicious vehicle driving slowly on Fatima Bhayat Street tonight. Residents in Rustenburg please be vigilant and lock your gates.",
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "2",
    area_id: "nw-8",
    area_name: "Mafikeng",
    province_name: "North West",
    user_id: "anon",
    category: "outage",
    content: "Water outage affecting most of Mafikeng CBD and surrounding suburbs. Magalies Water has been notified. Expected restoration by 6pm.",
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    id: "3",
    area_id: "nw-5",
    area_name: "Moses Kotane",
    province_name: "North West",
    user_id: "anon",
    category: "lost_found",
    content: "Found a golden Labrador near Mogwase village. No collar. Very friendly. Please contact if this is your dog — I have her safe at home.",
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "4",
    area_id: "nw-18",
    area_name: "Potchefstroom",
    province_name: "North West",
    user_id: "anon",
    category: "announcement",
    content: "Community Imbizo this Saturday at 10am at Frikkie Meyer Boulevard Community Hall. We'll be discussing load shedding schedules and the new traffic lights. All residents welcome.",
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: "5",
    area_id: "nw-2",
    area_name: "Madibeng",
    province_name: "North West",
    user_id: "anon",
    category: "alert",
    content: "Cable theft on the main road last night caused additional blackouts on top of scheduled load shedding. Eskom is aware — protect your generators.",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: "6",
    area_id: "nw-3",
    area_name: "Rustenburg",
    province_name: "North West",
    user_id: "anon",
    category: "lost_found",
    content: "Lost: black and white cat named Socks. Missing since Tuesday near Waterfall Mall area. She's microchipped. Reward offered — please message if seen.",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
];
